#!/usr/bin/python3

import sys
import os.path
from os import path
import subprocess

if len(sys.argv)<5:
    print("This script extracts a subset of traffic from a pcap file between [start] and [end] time in seconds (relative time).")
    print()
    print("An optional tolerance in second will be subtracted from start time, and added to end time.")
    print()
    print(f"Usage: {sys.argv[0]} <source pcap file> <destination pcap file> <start time> <end time> [tolerance]")
    sys.exit(0)

pcap_i=sys.argv[1]
pcap_o=sys.argv[2]

if not path.exists(pcap_i):
    print(f"Error: file '{pcap_i}' does not exist.")
    sys.exit(1)

try:
    start_t = int(sys.argv[3])
except ValueError:
    print("Error: start time must be a number.")
    sys.exit(1)

try:
    end_t = int(sys.argv[4])
except ValueError:
    print("Error: end time must be a number.")
    sys.exit(1)

if start_t>end_t:
    print("Error: start time is greater than end time")
    sys.exit(1)

if len(sys.argv)>5:
    try:
        tolerance = int(sys.argv[5])
        start_t -= tolerance
        end_t += tolerance
    except ValueError:
        print("Error: tolerance must be a number.")
        sys.exit(1)

if start_t<0:
    bstart_t = 0

cmd = ["tshark","-r", pcap_i,
           "-2", "-R", f"frame.time_relative >= {start_t} && frame.time_relative <= {end_t}",
           "-w", pcap_o]

try:
    subprocess.check_call(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
except subprocess.CalledProcessError:
    print("Error executing:", " ".join(cmd))
    sys.exit(1)
